name: Deploy CD

on:
  workflow_run:
    workflows: ["OmaLib CI"] 
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~
            if [ ! -d "oma-library" ]; then
              git clone -b main https://github.com/antonycarl/OMA-Library.git oma-library
            fi

            cd oma-library
            git pull

            echo "${{ secrets.ENV_FILE }}" > .env

            docker compose down
            docker compose pull
            docker compose up -d --build
          EOF